# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 12:12
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, help_text='200x200px', null=True, upload_to=core.utils.get_upload_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=core.utils.get_upload_path, verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='200x200px', null=True, upload_to=core.utils.get_upload_path, verbose_name='Photo'),
        ),
    ]
