# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170524_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='networks',
            field=models.ManyToManyField(related_name='candidates', to='users.Candidate', verbose_name='Networks'),
        ),
    ]
