# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170524_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Alias/Slug'),
        ),
    ]
