# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20170526_0256'),
        ('users', '0005_auto_20170525_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='networks',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='team_members',
        ),
        migrations.AddField(
            model_name='candidate',
            name='connections',
            field=models.ManyToManyField(related_name='_candidate_connections_+', through='recruit.Connection', to='users.Candidate', verbose_name='Connections'),
        ),
    ]
