# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170526_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='connections',
        ),
    ]
