# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170606_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='in_contract_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Open to new opportunities'), (2, 'Actively looking for new opportunities')], null=True, verbose_name='In Contract Status'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='out_contract_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Currently looking for new opportunities'), (2, 'Not looking for new opportunities')], null=True, verbose_name='Out of Contract Status'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Currently Looking for a new contract'), (2, 'Currently in Contract'), (3, 'Currently out of contract')], default=1, verbose_name='Status'),
        ),
    ]
