# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def migrate_candidate_skills(apps, schema_editor):
    """
        Populates new relationship from old one.
    """
    Candidate = apps.get_model('users', 'Candidate')
    CandidateSkill = apps.get_model('users', 'CandidateSkill')

    for candidate in Candidate.objects.all():
        for skill in candidate.skills.all():
            participant = CandidateSkill.objects.create(
                candidate=candidate,
                skill=skill,
                experience=0,
                created_at=timezone.now(),
                updated_at=timezone.now()
            )
            participant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0014_auto_20170608_1243'),
        ('users', '0010_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('experience', models.SmallIntegerField(verbose_name='Years of Experience')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_skills', to='users.Candidate', verbose_name='Candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='recruit.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Candidate Skill',
                'verbose_name_plural': 'Candidate Skills',
            },
        ),
        migrations.RunPython(migrate_candidate_skills),
    ]
