# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0014_auto_20170608_1243'),
        ('users', '0012_remove_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', through='users.CandidateSkill', to='recruit.Skill', verbose_name='Skills'),
        ),
    ]
