# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 10:53
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


def create_candidate_settings(apps, schema_editor):
    """
        Populates new relationship from old one.
    """
    Candidate = apps.get_model('users', 'Candidate')
    CandidateSettings = apps.get_model('users', 'CandidateSettings')

    for candidate in Candidate.objects.all():
        CandidateSettings.objects.create(
            candidate=candidate,
            created_at=timezone.now(),
            updated_at=timezone.now()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_candidate_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('auto_cv_download', models.BooleanField(default=False, verbose_name='Automatic Download of CV?')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.Candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Candidate Settings',
                'verbose_name_plural': 'Candidate Settings',
            },
        ),
        migrations.RunPython(create_candidate_settings),
    ]
