# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_candidatesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesettings',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.Candidate', verbose_name='Candidate'),
        ),
    ]
