# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 10:53
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def create_candidate_settings(apps, schema_editor):
    """
        Populates new relationship from old one.
    """
    Candidate = apps.get_model('users', 'Candidate')
    CandidateSettings = apps.get_model('users', 'CandidateSettings')

    CandidateSettings.objects.all().delete()

    for candidate in Candidate.objects.all():
        CandidateSettings.objects.create(
            candidate=candidate,
            created_at=timezone.now(),
            updated_at=timezone.now()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cvrequest'),
    ]

    operations = [
        migrations.RunPython(create_candidate_settings),
    ]
