# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_create_candidate_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('ip_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP address')),
                ('country_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country code')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country name')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('continent_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Continend code')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User location',
                'verbose_name_plural': 'User locations',
            },
        ),
    ]
