# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 01:43
from __future__ import unicode_literals

from django.db import migrations, models


def set_default_username(apps, schema_editor):
    """
        Populates new relationship from old one.
    """
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        user.username = user.slug
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170727_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.RunPython(set_default_username),
    ]
