# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_username_remove_dash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./_ only.', max_length=150, unique=True, validators=[users.validators.UsernameValidator()], verbose_name='Username'),
        ),
    ]
