# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 01:43
from __future__ import unicode_literals

import itertools

from django.db import migrations, models


def username_remove_id(apps, schema_editor):
    """
        Populates new relationship from old one.
    """
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        user.username = username_copy = '{}{}'.format(user.first_name, user.last_name).replace(' ', '')
        for i in itertools.count(1):
            if not User.objects.filter(username=user.username).exists():
                break
            user.username = '{}{}'.format(username_copy, i)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20170823_0403'),
    ]

    operations = [
        migrations.RunPython(username_remove_id),
    ]
