# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('status', models.IntegerField(choices=[(0, 'Recruitment'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=0, verbose_name='Status')),
                ('subject', models.CharField(help_text='Short description of your issue, like "server in the room #215 is down".', max_length=200, verbose_name='Issue Subject')),
                ('description', models.TextField(verbose_name='Problem Description')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Issue unique id')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'IT Support Issue',
                'verbose_name_plural': 'IT Support Issues',
            },
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('from_state', models.IntegerField(choices=[(0, 'Recruitment'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=0, verbose_name='Initial state')),
                ('to_state', models.IntegerField(choices=[(0, 'Recruitment'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=3, verbose_name='Final state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
