# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='statechange',
            name='from_state',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=0, verbose_name='Initial state'),
        ),
        migrations.AlterField(
            model_name='statechange',
            name='to_state',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=3, verbose_name='Final state'),
        ),
    ]
