# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20170824_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('from_state', models.IntegerField(choices=[(0, 'Open'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=0, verbose_name='Initial state')),
                ('to_state', models.IntegerField(choices=[(0, 'Open'), (1, 'Waiting Client'), (2, 'Waiting Provider'), (3, 'Closed')], default=3, verbose_name='Final state')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Issue', verbose_name='Referred Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StateChange',
        ),
    ]
