# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170525_1607'),
        ('recruit', '0002_auto_20170523_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('connection_type', models.IntegerField(choices=[(1, 'Network'), (2, 'Team Member')], verbose_name='Connection Type')),
                ('uuid', models.SlugField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('request_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_recipients', to='users.Candidate', verbose_name='Request Recipient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='users.Candidate', verbose_name='Requested By')),
            ],
            options={
                'verbose_name_plural': 'Connection Requests',
                'verbose_name': 'Connection Request',
            },
        ),
    ]
