# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170525_1607'),
        ('recruit', '0003_connectionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('connection_type', models.IntegerField(choices=[(1, 'Network'), (2, 'Team Member')], verbose_name='Connection Type')),
                ('connectee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Candidate', verbose_name='Connectee')),
                ('connecter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Candidate', verbose_name='Connecter')),
            ],
            options={
                'verbose_name_plural': 'Connections',
                'verbose_name': 'Connection',
            },
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='request_recipient',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='connectee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectee_requests', to='users.Candidate', verbose_name='Request Recipient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='connecter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecter_requests', to='users.Candidate', verbose_name='Requested By'),
            preserve_default=False,
        ),
    ]
