# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170526_0256'),
        ('recruit', '0005_auto_20170526_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('connection_type', models.IntegerField(choices=[(1, 'Network'), (2, 'Team Member')], verbose_name='Connection Type')),
                ('uuid', models.SlugField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('connectee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Candidate', verbose_name='Connectee')),
                ('connecter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Candidate', verbose_name='Connecter')),
            ],
            options={
                'verbose_name': 'Connection invitation',
                'verbose_name_plural': 'Connection invitations',
            },
        ),
    ]
