# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170526_0256'),
        ('recruit', '0007_auto_20170529_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruit.JobPost', verbose_name='Job Post')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Candidate', verbose_name='Referred By')),
                ('referred_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Candidate', verbose_name='Referred To')),
            ],
            options={
                'verbose_name_plural': 'Job Referrals',
                'verbose_name': 'Job Referral',
            },
        ),
    ]
