# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_jobreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connectee_account_type',
            field=models.IntegerField(choices=[(1, 'Candidate'), (2, 'Agent')], default=1, verbose_name='Connectee Account Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='connecter_account_type',
            field=models.IntegerField(choices=[(1, 'Candidate'), (2, 'Agent')], default=1, verbose_name='Connecter Account Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectioninvite',
            name='connectee_account_type',
            field=models.IntegerField(choices=[(1, 'Candidate'), (2, 'Agent')], default=1, verbose_name='Connectee Account Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectioninvite',
            name='connecter_account_type',
            field=models.IntegerField(choices=[(1, 'Candidate'), (2, 'Agent')], default=1, verbose_name='Connecter Account Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='connectee_account_type',
            field=models.IntegerField(choices=[(1, 'Candidate'), (2, 'Agent')], default=1, verbose_name='Connectee Account Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='connecter_account_type',
            field=models.IntegerField(choices=[(1, 'Candidate'), (2, 'Agent')], default=1, verbose_name='Connecter Account Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='connectee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Connectee'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connecter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Connecter'),
        ),
        migrations.AlterField(
            model_name='connectioninvite',
            name='connecter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Connecter'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='connectee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectee_requests', to=settings.AUTH_USER_MODEL, verbose_name='Connectee'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='connecter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecter_requests', to=settings.AUTH_USER_MODEL, verbose_name='Connecter'),
        ),
    ]
