# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_auto_20170531_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='connectee_account_type',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='connecter_account_type',
        ),
        migrations.RemoveField(
            model_name='connectioninvite',
            name='connectee_account_type',
        ),
        migrations.RemoveField(
            model_name='connectioninvite',
            name='connecter_account_type',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='connectee_account_type',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='connecter_account_type',
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.IntegerField(choices=[(1, 'Network'), (2, 'Team Member'), (3, 'Agent')], verbose_name='Connection Type'),
        ),
        migrations.AlterField(
            model_name='connectioninvite',
            name='connection_type',
            field=models.IntegerField(choices=[(1, 'Network'), (2, 'Team Member'), (3, 'Agent')], verbose_name='Connection Type'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='connection_type',
            field=models.IntegerField(choices=[(1, 'Network'), (2, 'Team Member'), (3, 'Agent')], verbose_name='Connection Type'),
        ),
    ]
