# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170606_1310'),
        ('recruit', '0013_userreferral'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Is Viewed?')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='users.Candidate', verbose_name='Candidate')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='recruit.JobPost', verbose_name='Job Post')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='applications',
            field=models.ManyToManyField(related_name='applications', through='recruit.JobApplication', to='users.Candidate', verbose_name='Application'),
        ),
    ]
