# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0017_auto_20170726_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.IntegerField(choices=[(1, 'Network'), (2, 'Team'), (3, 'IT Support')], verbose_name='Connection Type'),
        ),
    ]
