# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20170908_1946'),
        ('recruit', '0018_auto_20170824_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('is_interested', models.BooleanField(default=False, verbose_name='Is interested?')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_interested', to='users.Candidate', verbose_name='Candidate')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_interested', to='recruit.JobPost', verbose_name='Job Post')),
            ],
            options={
                'verbose_name': 'Job Interest',
                'verbose_name_plural': 'Job Interests',
            },
        ),
    ]
