# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 12:12
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170523_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.get_upload_path, verbose_name='Logo'),
        ),
    ]
