# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_user_to_owner(apps, schema_editor):
    """
        Populates new relationship from old one.
    """
    Company = apps.get_model('companies', 'Company')

    for company in Company.objects.all():
        company.agent = company.owner.agent
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_candidate_skills'),
        ('companies', '0004_auto_20170625_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_owned', to='users.Agent', verbose_name='Major company representative'),
        ),
        migrations.RunPython(migrate_user_to_owner)
    ]
