# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_company_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='agent',
            new_name='owner',
        ),
    ]
