# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cvrequest'),
        ('companies', '0007_auto_20170625_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvitation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='invite_key',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='sent_to',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='sent_to_user',
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='invitee_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Invitee Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='inviter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Agent', verbose_name='Inviter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Request Invitation key'),
        ),
    ]
