# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_auto_20170708_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.IntegerField(choices=[(1, 'Recruitment'), (2, 'Support')], default=1, verbose_name='Company Type'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_owned', to=settings.AUTH_USER_MODEL, verbose_name='Major company representative'),
        ),
    ]
