# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 04:56
from __future__ import unicode_literals

from django.db import migrations


def save_company_owner_to_user(apps, schema_editor):
    """
    Change company owner from agent to user
    """
    Company = apps.get_model('companies', 'Company')

    for company in Company.objects.all():
        company.user = company.owner.user
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20170723_0543'),
    ]

    operations = [
        migrations.RunPython(save_company_owner_to_user),
    ]
