# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_company_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='owner',
        ),
    ]
