# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20170607_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='participant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.Conversation', verbose_name='Conversation'),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_read_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.Message', verbose_name='Last read message', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='users_new',
            field=models.ManyToManyField(related_name='conversations_new', through='chat.Participant', to=settings.AUTH_USER_MODEL, verbose_name='Conversation participants'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('user', 'conversation')]),
        ),
    ]
