# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 11:28
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def make_many_participants(apps, schema_editor):
    """
        Populates new relationship from old one.
    """
    Conversation = apps.get_model('chat', 'Conversation')
    Participant = apps.get_model('chat', 'Participant')

    for conversation in Conversation.objects.all():
        for user in conversation.users.all():
            participant = Participant.objects.create(
                last_read_message=conversation.messages.all().order_by('-created_at').first(),
                user=user,
                conversation=conversation,
                created_at=timezone.now(),
                updated_at=timezone.now()
            )
            participant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170608_1228'),
    ]

    operations = [
        migrations.RunPython(make_many_participants)
    ]
