# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_remove_conversation_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='users_new',
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(related_name='conversations', through='chat.Participant', to=settings.AUTH_USER_MODEL, verbose_name='Conversation participants'),
        ),
    ]
