# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170608_1056'),
        ('chat', '0007_auto_20170608_1243'),
    ]

    operations = [
    ]
