# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_merge_20170609_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.Message', verbose_name='Last read message'),
        ),
    ]
