# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_auto_20170611_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.IntegerField(choices=[(0, 'User chat'), (1, 'Group chat')], default=0, help_text='Conversation type based on how it was created.', verbose_name='Conversation Type'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conversation name'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Conversation owner'),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_status',
            field=models.IntegerField(choices=[(0, 'Participant accepted'), (1, 'Participant pending'), (2, 'Participant declined')], default=0, help_text='Conversation type based on how it was created.', verbose_name='Conversation Type'),
        ),
    ]
