# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20170620_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('text', models.TextField(verbose_name='Invite text')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='chat.Conversation', verbose_name='Conversation to invite into')),
            ],
            options={
                'verbose_name': 'Group invite',
                'verbose_name_plural': 'Group invites',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.GroupInvite', verbose_name='Event linked to message'),
        ),
    ]
