# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20170621_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='participant_status',
        ),
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.IntegerField(choices=[(0, 'Participant accepted'), (1, 'Participant pending'), (2, 'Participant declined')], default=0, help_text='Participant invite acceptance status.', verbose_name='Participant status'),
        ),
    ]
