# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20170623_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinvite',
            old_name='group',
            new_name='conversation',
        ),
    ]
