# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20170623_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvite',
            name='conversation',
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.Participant', verbose_name='Participant receiving invite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='status',
            field=models.IntegerField(choices=[(0, 'Invite accepted'), (1, 'Invite pending'), (2, 'Invite declined')], default=1, help_text='Group chat invite acceptance status.', verbose_name='Participant status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group_invite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.GroupInvite', verbose_name='Invite linked to message'),
        ),
    ]
