# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20170628_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group_invite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.GroupInvite', verbose_name='Invite linked to message'),
        ),
    ]
