# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
