# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 09:27
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_attachment_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='File size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=core.utils.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.Message', verbose_name='Message'),
        ),
    ]
